### ISSUE TITLE
疑似kotlinx.coroutines内部的报错

### ISSUE THREAD

**Issue by CuteReimu** [CuteReimu/TheMessage#65]
该错误被打印在控制台，并未打印在log4j日志中。疑似是`kotlinx.coroutines`内部的错误，暂时不知道原因。

```
22:02:46.188 INFO com.fengsheng.phase.DrawPhase.resolve(DrawPhase.kt:17) 1号[白小年]的回合开始了
22:02:46.188 DEBUG com.fengsheng.HumanPlayer.send(HumanPlayer.kt:40) send@a8d2a529 len: 4 notify_phase_toc | current_player_id: 1 waiting_player_id: 1
22:02:46.188 DEBUG com.fengsheng.HumanPlayer.send(HumanPlayer.kt:40) send@a8d2a529 len: 2 sync_deck_num_toc | num: 68
22:02:46.188 INFO com.fengsheng.Player.draw(Player.kt:101) 1号[白小年]摸了[红色调包, 黑色澄清, 黑色红方-1试探]，现在有6张手牌
22:02:46.188 DEBUG com.fengsheng.HumanPlayer.send(HumanPlayer.kt:40) send@a8d2a529 len: 4 add_card_toc | player_id: 1 unknown_card_count: 3
22:02:46.188 DEBUG com.fengsheng.HumanPlayer.send(HumanPlayer.kt:40) send@a8d2a529 len: 8 notify_phase_toc | current_player_id: 1 current_phase: Main_Phase waiting_player_id: 1 waiting_second: 20
22:02:48.287 INFO com.fengsheng.card.WeiBi.execute(WeiBi.kt:47) 1号[白小年]对4号[肥原龙川]使用了红色威逼
Exception in thread "DefaultDispatcher-worker-2" java.lang.NoClassDefFoundError: kotlinx/coroutines/CoroutinesInternalError
        at kotlinx.coroutines.DispatchedTask.handleFatalException(DispatchedTask.kt:144)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.ClassNotFoundException: kotlinx.coroutines.CoroutinesInternalError
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 6 more
```

**Comment by CuteReimu** [comment]
```kotlin
    public fun handleFatalException(exception: Throwable?, finallyException: Throwable?) {
        if (exception === null && finallyException === null) return
        if (exception !== null && finallyException !== null) {
            exception.addSuppressedThrowable(finallyException)
        }

        val cause = exception ?: finallyException
        val reason = CoroutinesInternalError("Fatal exception in coroutines machinery for $this. " +
                "Please read KDoc to 'handleFatalException' method and report this incident to maintainers", cause!!)
        handleCoroutineException(this.delegate.context, reason)
    }
```
像是倒数第四行那个`CoroutinesInternalError`类不存在，但是从打出来的jar包里确实又存在：

```kotlin
// IntelliJ API Decompiler stub source generated from a class file
// Implementation of methods is not available

package kotlinx.coroutines

internal final class CoroutinesInternalError public constructor(message: kotlin.String, cause: kotlin.Throwable) : kotlin.Error /* = java.lang.Error */ {
}
```

**Comment by CuteReimu** [comment]
再次出现了类似的问题：

```
Exception in thread "nioEventLoopGroup-5-1" java.lang.NoClassDefFoundError: io/netty/buffer/PoolArena$1
        at io.netty.buffer.PoolArena.freeChunk(PoolArena.java:261)
        at io.netty.buffer.PoolThreadCache$MemoryRegionCache.freeEntry(PoolThreadCache.java:445)
        at io.netty.buffer.PoolThreadCache$MemoryRegionCache.free(PoolThreadCache.java:409)
        at io.netty.buffer.PoolThreadCache$MemoryRegionCache.free(PoolThreadCache.java:401)
        at io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:266)
        at io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:257)
        at io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:215)
        at io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.onRemoval(PooledByteBufAllocator.java:546)
        at io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.onRemoval(PooledByteBufAllocator.java:507)
        at io.netty.util.concurrent.FastThreadLocal.remove(FastThreadLocal.java:259)
        at io.netty.util.concurrent.FastThreadLocal.removeAll(FastThreadLocal.java:67)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:1050)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: io.netty.buffer.PoolArena$1
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)   
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 15 more
```

都是`java.lang.ClassNotFoundException`，有可能是打的包有问题

**Comment by CuteReimu** [comment]
```
Exception in thread "DefaultDispatcher-worker-1" java.lang.NoClassDefFoundError: kotlinx/coroutines/CoroutinesInternalError
        at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:146)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:117)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.lang.ClassNotFoundException: kotlinx.coroutines.CoroutinesInternalError
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 6 more
```
这一次是`kotlinx.coroutines.CoroutinesInternalError`

**Comment by CuteReimu** [comment]
与 #96 相似，似乎是因为直接覆盖了jar包后，还未重启，因此原进程找类时，找不到原先的jar包里的类，而导致的问题。
