### ISSUE TITLE
【严重】服务器偶尔会挂掉

### ISSUE THREAD

**Issue by CuteReimu** [CuteReimu/TheMessage#96]
> 有没有可能是因为直接覆盖了jar包后，还未重启，因此原进程找类时，找不到原先的jar包里的类，也无法去新jar包里面找？

错误日志如下：

```
Exception in thread "nioEventLoopGroup-7-3" java.lang.NoClassDefFoundError: io/netty/buffer/PoolArena$1
        at io.netty.buffer.PoolArena.freeChunk(PoolArena.java:262)
        at io.netty.buffer.PoolThreadCache$MemoryRegionCache.freeEntry(PoolThreadCache.java:444)
        at io.netty.buffer.PoolThreadCache$MemoryRegionCache.free(PoolThreadCache.java:408)
        at io.netty.buffer.PoolThreadCache$MemoryRegionCache.free(PoolThreadCache.java:400)
        at io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:266)
        at io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:257)
        at io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:215)
        at io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.onRemoval(PooledByteBufAllocator.java:542)
        at io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.onRemoval(PooledByteBufAllocator.java:503)
        at io.netty.util.concurrent.FastThreadLocal.remove(FastThreadLocal.java:259)
        at io.netty.util.concurrent.FastThreadLocal.removeAll(FastThreadLocal.java:67)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:1050)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: io.netty.buffer.PoolArena$1
        ... 15 more
18:17:05.128 DEBUG com.fengsheng.network.WebSocketServerChannelHandler.channelRead0(WebSocketServerChannelHandler.kt:50) recv@06beaef0 len: 8 send_message_card_tos | card_id: 54 target_player_id: 1 seq: 29 
18:17:05.129 INFO com.fengsheng.phase.OnSendCard.resolve(OnSendCard.kt:33) 4号[SP李宁玉]传出了蓝色澄清，方向是Up，传给了0号[小九]
Exception in thread "DefaultDispatcher-worker-2" java.lang.NoClassDefFoundError: kotlinx/coroutines/CoroutinesInternalError
        at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:146)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:117)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.lang.ClassNotFoundException: kotlinx.coroutines.CoroutinesInternalError
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 6 more
18:17:35.562 INFO com.fengsheng.network.WebSocketServerChannelHandler.channelActive(WebSocketServerChannelHandler.kt:68) session connected: c043f6fb /39.144.141.45:14810
18:17:35.567 DEBUG io.netty.handler.codec.http.websocketx.WebSocketServerHandshaker.handshake(WebSocketServerHandshaker.java:200) [id: 0xc043f6fb, L:/10.0.4.10:12222 - R:/39.144.141.45:14810] WebSocket version V13 server handshake
18:17:35.567 DEBUG io.netty.handler.codec.http.websocketx.WebSocketServerHandshaker13.newHandshakeResponse(WebSocketServerHandshaker13.java:172) WebSocket version 13 server handshake key: vHyIRVnrbrtPFK8e2swFMg==, response: rfqdBvvrfXaaTaMOxjdToFcv5JY=
18:17:37.366 DEBUG com.fengsheng.network.WebSocketServerChannelHandler.channelRead0(WebSocketServerChannelHandler.kt:50) recv@c043f6fb len: 78 join_room_tos | version: 105 name: "风间" device: "8c12c48e2fd6c1d4b118b96688d506e6" password: "e10adc3949ba59abbe56e057f20f883e" 
18:17:55.235 INFO com.fengsheng.network.WebSocketServerChannelHandler.channelInactive(WebSocketServerChannelHandler.kt:85) session closed: 23c732ae /183.46.208.193:29112
18:17:55.358 INFO com.fengsheng.network.WebSocketServerChannelHandler.channelActive(WebSocketServerChannelHandler.kt:68) session connected: a04cf04c /183.46.208.193:29123
18:17:55.359 DEBUG io.netty.handler.codec.http.websocketx.WebSocketServerHandshaker.handshake(WebSocketServerHandshaker.java:200) [id: 0xa04cf04c, L:/10.0.4.10:12222 - R:/183.46.208.193:29123] WebSocket version V13 server handshake
18:17:55.359 DEBUG io.netty.handler.codec.http.websocketx.WebSocketServerHandshaker13.newHandshakeResponse(WebSocketServerHandshaker13.java:172) WebSocket version 13 server handshake key: iPZkUc0AyUZA6dUpniPDbg==, response: 4NsJdu1wCgsZWblrAm/Zx+HCGrg=
18:17:55.978 DEBUG com.fengsheng.network.WebSocketServerChannelHandler.channelRead0(WebSocketServerChannelHandler.kt:50) recv@a04cf04c len: 75 join_room_tos | version: 105 name: "斌" device: "dc9d211cfd86c648d0c19d105252c386" password: "e10adc3949ba59abbe56e057f20f883e" 
Exception in thread "nioEventLoopGroup-4-1" java.lang.NoClassDefFoundError: org/apache/log4j/spi/ThrowableInformation
        at org.apache.log4j.spi.LoggingEvent.<init>(LoggingEvent.java:165)
        at org.apache.log4j.Category.forcedLog(Category.java:391)
        at org.apache.log4j.Category.log(Category.java:856)
        at io.netty.util.internal.logging.Log4JLogger.error(Log4JLogger.java:595)
        at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:864)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:500)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
        at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:625)
        at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:97)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:1059)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.spi.ThrowableInformation
        ... 13 more
```

**Comment by CuteReimu** [comment]
基本确定是因为直接覆盖了jar包后，还未重启，因此原进程找类时，找不到原先的jar包里的类，而导致的问题。
